name: deploy-to-ftp

description: Deploy a folder to your server via ftp

inputs:
  user:
    required: true
    description: Ftp user
  password:
    required: true
    description: Ftp password
  port:
    description: FTP port
    required: false
    default: "21"
  host:
    description: FTP host url
    required: true
  path:
    description: Path to the folder to deploy (from root)
    required: true
  into:
    description: Where to place the files in your ftp
    required: true

runs:
  using: node12
  main: dist/index.js
